export { Root } from './root';
export { Nav } from './nav';
export { Home } from './home';
export { Gallery } from './gallery';
export { About } from './about';
export { Benefits } from './benefits';
export { Info } from './info';
export { Contact } from './contact';
export { Content } from './content';